### ISSUE TITLE
隐写透明底图片时，会将透明底填充颜色

### ISSUE THREAD

**Issue by sutuplus** [ivanwhaf/img-stegano#1]
填充颜色对原图影响非常大，能否优化这个，感谢作者🙏

**Comment by ivanwhaf** [comment]
透明图片就是png图片多了一个alpha通道，是rgb+alpha四通道，判断一下第四个通道如果是透明就跳过不隐写，第四个通道不透明才进行隐写。下个版本有空会改进。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ivanwhaf/img-stegano"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 下午5:46
收件人:&nbsp;"ivanwhaf/img-stegano"<img-stegano@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ivanwhaf/img-stegano] 隐写透明底图片时，会将透明底填充颜色 (#1)





 
填充颜色对原图影响非常大，能否优化这个，感谢作者🙏

**Comment by sutuplus** [comment]
懂了，感谢回复！！！我想判断背景是否透明去跳过处理，但是没有成功，cv2和PIL image里没有方法直接判断图是不是RGPA(默认只显示3通道ToT)

Ivan <notifications@github.com>于2020年12月18日 周五下午10:16写道：

**Comment by sutuplus** [comment]
关闭问题
